name: Glacier.ML CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            libeigen3-dev \
            libopenblas-dev \
            libomp-dev

      - name: Configure CMake
        run: cmake -B cmake-build-benchmark -G Ninja -DCMAKE_BUILD_TYPE=Debug

      - name: Build Targets
        run: cmake --build cmake-build-benchmark --target test_logr

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure